server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-driver-route
              uri: lb://user-driver-service
              predicates:
                - Path=/api/v1/auth/**, /api/v1/users/**, /api/v1/drivers/**
            - id: location-service-route
              uri: lb://location-service
              predicates:
                - Path=/api/v1/locations/**
            - id: location-websocket-route
              uri: lb:ws://location-service
              predicates:
                - Path=/ws-location/**
            - id: booking-service-route
              uri: lb://booking-service
              predicates:
                - Path=/api/v1/bookings/**
            - id: booking-websocket-route
              uri: lb:ws://booking-service
              predicates:
                - Path=/ws-booking/**
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOriginPatterns: "*"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970